rabbit:
  host: rabbit
  port: 5672
  user: user
  password: password
  routing_key: image
  queue_name: image

tmp_dir: /tmp

logging:
  root_log_level: 0
  logstash:
    host: elk
    port: 5046
    app_extra:
      service: image-api
  modules:
    - name: urllib3.connectionpool
      log_level: 30
    - name: pika
      log_level: 30

pg:
  host: db
  port: 5432
  user: postgres
  password: postgres
  database: my_db
